feat: add config flap / drift detection for tf (#854)
* feat: add config flap / drift detection for tf

the idea here is that since we dont run them atm longterm to at least check after the immediate apply where theres still a drift or not

meaning something would need to be fixed in the config, otherwise not good ux

* chore: change drift to reuseable action

* fix: consume extra-args input directly

* fix: add newline due to multiline input

* fix: azure tf config flap

* fix: azure golden file

* fix: switch to single quotes

* chore: only warn for drift on rosa due to common hcp module drift

they set a null value and change it eventually when the cluster is really ready

* fix: rosa dual-region tf flap mismatch

* fix: bump accidental checkout downgrade

* chore: switch to var-file

* chore: fix formating

diff --git a/.github/actions/aws-openshift-rosa-hcp-single-region-create/action.yml b/.github/actions/aws-openshift-rosa-hcp-single-region-create/action.yml
--- a/.github/actions/aws-openshift-rosa-hcp-single-region-create/action.yml
+++ b/.github/actions/aws-openshift-rosa-hcp-single-region-create/action.yml
@@ -239,6 +239,17 @@ runs:
           with:
               raw-tags: ${{ inputs.tags }}
 
+        - name: Generate tfvars file - Cluster
+          id: generate-tfvars-cluster
+          shell: bash
+          working-directory: ${{ inputs.tf-modules-path }}/aws/openshift/rosa-hcp-single-region/terraform/cluster/
+          run: |
+              set -euo pipefail
+
+              cat > terraform.tfvars <<EOF
+              default_tags = ${{ steps.sanitize-tags.outputs.sanitized_tags }}
+              EOF
+
         - name: Terraform Plan - Cluster
           id: plan-cluster
           working-directory: ${{ inputs.tf-modules-path }}/aws/openshift/rosa-hcp-single-region/terraform/cluster/
@@ -279,7 +290,7 @@ runs:
               echo "Displaying templated cluster.tf file:"
               cat cluster.tf
 
-              terraform plan -no-color -var='default_tags=${{ steps.sanitize-tags.outputs.sanitized_tags }}' -out rosa.plan
+              terraform plan -no-color -var-file=terraform.tfvars -out rosa.plan
 
         - name: Terraform Apply - Cluster
           id: apply-cluster
@@ -297,6 +308,17 @@ runs:
 
               export vpc_id="$(terraform output -raw vpc_id)"
               echo "vpc_id=$vpc_id" | tee -a "$GITHUB_OUTPUT"
+
+        - name: Terraform Drift Detection - Cluster
+          uses: ./.github/actions/internal-terraform-drift-detect
+          id: drift-detect-cluster
+          with:
+              working-directory: ${{ inputs.tf-modules-path }}/aws/openshift/rosa-hcp-single-region/terraform/cluster/
+              plan-extra-args: |
+                  -var-file=terraform.tfvars \
+              fail-on-drift: 'false' # not failing on drift as there may be an expected drift due to hcp module drifting - cluster_console_url
+          env:
+              RHCS_TOKEN: ${{ inputs.rh-token }}
 
         - name: Terraform Init - VPN
           id: init-vpn
@@ -319,6 +341,18 @@ runs:
 
               terraform validate -no-color
 
+        - name: Generate tfvars file - VPN
+          id: generate-tfvars-vpn
+          shell: bash
+          working-directory: ${{ inputs.tf-modules-path }}/aws/openshift/rosa-hcp-single-region/terraform/vpn/
+          run: |
+              set -euo pipefail
+
+              cat > terraform.tfvars <<EOF
+              default_tags = ${{ steps.sanitize-tags.outputs.sanitized_tags }}
+              vpc_id="${{ steps.apply-cluster.outputs.vpc_id }}"
+              EOF
+
         - name: Terraform Plan - VPN
           id: plan-vpn
           if: inputs.vpn-enabled == 'true'
@@ -339,8 +373,7 @@ runs:
               cat vpn.tf
 
               terraform plan -no-color \
-                -var='default_tags=${{ steps.sanitize-tags.outputs.sanitized_tags }}' \
-                -var="vpc_id=${{ steps.apply-cluster.outputs.vpc_id }}" \
+                -var-file=terraform.tfvars \
                 -out vpn.plan
 
         - name: Terraform Apply - VPN
@@ -358,6 +391,15 @@ runs:
               echo "::add-mask::$vpn_client_configs"
 
               echo "vpn_endpoint=$(terraform output -json vpn_endpoint)" | tee -a "$GITHUB_OUTPUT"
+
+        - name: Terraform Drift Detection - VPN
+          id: drift-detect-vpn
+          if: inputs.vpn-enabled == 'true'
+          uses: ./.github/actions/internal-terraform-drift-detect
+          with:
+              working-directory: ${{ inputs.tf-modules-path }}/aws/openshift/rosa-hcp-single-region/terraform/vpn/
+              plan-extra-args: |
+                  -var-file=terraform.tfvars \
 
         ### End of terraform
 
