fix: separate service export from single step due to working directory for connectors test

diff --git a/.github/actions/internal-multi-region-tests/action.yml b/.github/actions/internal-multi-region-tests/action.yml
--- a/.github/actions/internal-multi-region-tests/action.yml
+++ b/.github/actions/internal-multi-region-tests/action.yml
@@ -228,6 +228,24 @@ runs:
 
               go test --count=1 -v -timeout 20m -failfast -run TestZeebeClusterScaleUpBothBrokersAndPartitions
 
+        - name: Deploy connector webhook flow in multi-region setup
+          shell: bash
+          working-directory: ./aws/kubernetes/eks-dual-region/test
+          run: |
+              set -euo pipefail
+
+              go test --count=1 -v -timeout 20m -failfast -run TestConnectorWebhookFlowDeploy
+
+        # It's separated to allow re-exporting the Services for OpenShift
+        - name: Re-export services (OpenShift)
+          if: inputs.post-failback-script != ''
+          shell: bash
+          run: |
+              set -euo pipefail
+
+              echo "Running post-failback script to re-export services to expose mock server..."
+              ${{ inputs.post-failback-script }}
+
         - name: Test connector webhook flow in multi-region setup
           shell: bash
           working-directory: ./aws/kubernetes/eks-dual-region/test
@@ -235,13 +253,6 @@ runs:
               DISTRIBUTION: ${{ inputs.distribution }}
           run: |
               set -euo pipefail
-
-              go test --count=1 -v -timeout 20m -failfast -run TestConnectorWebhookFlowDeploy
-
-              if [ "${{ inputs.post-failback-script }}" != "" ]; then
-                echo "Running post-failback script to re-export services before Connector Webhook Flow test..."
-                ${{ inputs.post-failback-script }}
-              fi
 
               go test --count=1 -v -timeout 10m -failfast -run TestConnectorWebhookFlowTest
 
