fix fresh namespace

diff --git a/.github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml b/.github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml
--- a/.github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml
+++ b/.github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml
@@ -270,20 +270,34 @@ jobs:
                   rm encrypted_kubeconfig.enc
                   chmod 600 "$HOME/.kube/config"
 
-            - name: 🛠️ Prepare a FRESH deployment for generic/openshift/single-region
+            - name: 🏗️ Prepare a fresh namespace for the tests
+              # we need to retry due as the cluster has just been created and the permissions are sometime refused
+              uses: nick-fields/retry@7152eba30c6575329ac0576536151aca5a72780e # v3
+              id: kube_config
+              with:
+                  timeout_minutes: 10
+                  max_attempts: 40
+                  shell: bash
+                  retry_wait_seconds: 15
+                  command: |
+                      : # see https://github.com/nick-fields/retry/issues/133
+                      set -o errexit
+                      set -o pipefail
+
+                      # Delete the namespace to ensure a fresh start
+                      if kubectl get namespace "$TEST_NAMESPACE" &>/dev/null; then
+                        kubectl delete namespace "$TEST_NAMESPACE" --wait
+                        while kubectl get namespace "$TEST_NAMESPACE" &>/dev/null; do
+                            echo "Namespace $TEST_NAMESPACE still being deleted, waiting..."
+                            sleep 5
+                        done
+                      fi
+
+                      kubectl create namespace "$TEST_NAMESPACE"
+
+            - name: 🛠️ Assemble deployment values of generic/openshift/single-region
               run: |
                   set -euxo pipefail # tolerate, nothing.
-
-                  # Delete the namespace to ensure a fresh start
-                  if kubectl get namespace "$TEST_NAMESPACE" &>/dev/null; then
-                    kubectl delete namespace "$TEST_NAMESPACE" --wait
-                    while kubectl get namespace "$TEST_NAMESPACE" &>/dev/null; do
-                        echo "Namespace $TEST_NAMESPACE still being deleted, waiting..."
-                        sleep 5
-                    done
-                  fi
-
-                  kubectl create namespace "$TEST_NAMESPACE"
 
                   echo "Construct the values.yml file"
 
