feat(rosa): Add retry logic to ACM installation (#409) (#433)
Co-authored-by: Balázs <96087935+bkenez@users.noreply.github.com>

diff --git a/.github/workflows/aws_openshift_rosa_hcp_dual_region_tests.yml b/.github/workflows/aws_openshift_rosa_hcp_dual_region_tests.yml
--- a/.github/workflows/aws_openshift_rosa_hcp_dual_region_tests.yml
+++ b/.github/workflows/aws_openshift_rosa_hcp_dual_region_tests.yml
@@ -32,6 +32,11 @@ on:
                 description: Whether to enable the tests.
                 type: boolean
                 default: true
+            notify_back_error_message:
+                description: Used by rerun-failed-run
+                required: false
+                type: string
+
 
 # limit to a single execution per actor of this workflow
 concurrency:
@@ -75,6 +80,11 @@ jobs:
         outputs:
             should_skip: ${{ steps.skip_check.outputs.should_skip }}
         steps:
+            - name: Display notify_back_error_message if present
+              if: ${{ inputs.notify_back_error_message != '' }}
+              run: |
+                  echo "A previous workflow failed but has attempted to retry: ${{ inputs.notify_back_error_message }}"
+                  exit 1
             - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
             - name: Check labels
               id: skip_check
@@ -352,6 +362,53 @@ jobs:
                   ./aws/openshift/${{ matrix.scenario.name }}/procedure/get-your-copy.sh
                   tree
 
+            - name: Ensure ACM and associated MultiCluster are not installed (in case of retry)
+              timeout-minutes: 20
+              run: |
+                  set -euo pipefail
+
+                  echo "Uninstalling ManagedClusterSet..."
+                  oc --context="$CLUSTER_1_NAME" delete -f ./generic/openshift/dual-region/procedure/acm/managed-cluster-set.yml || true
+                  echo "Waiting for ManagedClusterSet to be deleted..."
+
+                  while oc --context="$CLUSTER_1_NAME" get managedclusterset --all-namespaces | grep -q .; do
+                    echo "Still waiting for ManagedClusterSet to be deleted..."
+                    sleep 10
+
+                    oc --context="$CLUSTER_1_NAME" patch mch MultiClusterHub --type='merge' -p '{"metadata":{"finalizers":[]}}' -n open-cluster-management
+                  done
+
+                  echo "Uninstalling MultiClusterHub..."
+                  # needed as described in https://access.redhat.com/solutions/7116241
+                  if oc --context="$CLUSTER_1_NAME" get clusterrole open-cluster-management:cluster-manager-admin >/dev/null 2>&1; then
+                    oc --context="$CLUSTER_1_NAME" delete clusterrole open-cluster-management:cluster-manager-admin
+                  fi
+
+                  oc --context="$CLUSTER_1_NAME" delete -f ./generic/openshift/dual-region/procedure/acm/multi-cluster-hub.yml || true
+
+                  SECONDS=0
+                  echo "Waiting for MultiClusterHub to be deleted..."
+                  while oc --context="$CLUSTER_1_NAME" get multiclusterhub -n open-cluster-management &>/dev/null; do
+                    echo "Still waiting for MultiClusterHub to be deleted..."
+                    sleep 10
+
+                    # manually finilalize as described in https://access.redhat.com/solutions/7116241
+                    if [ $SECONDS -ge 100 ]; then
+                      echo "Uninstallation of MultiClusterHub is stuck - enforcing finalizers!"
+                      oc --context="$CLUSTER_1_NAME" patch mch MultiClusterHub --type='merge' -p '{"metadata":{"finalizers":[]}}' -n open-cluster-management
+                    fi
+                  done
+
+                  echo "Uninstalling ACM Install Manifest..."
+                  oc --context="$CLUSTER_1_NAME" delete -f ./generic/openshift/dual-region/procedure/acm/install-manifest.yml || true
+                  echo "Waiting for MultiClusterEngine to be deleted..."
+                  while oc --context="$CLUSTER_1_NAME" get multiclusterengine -n open-cluster-management &>/dev/null; do
+                    echo 'Still waiting...'
+                    sleep 10
+                  done
+
+                  echo "ACM and related resources successfully uninstalled."
+
             - name: 🚢 Configure ACM
               timeout-minutes: 20
               env:
@@ -359,23 +416,39 @@ jobs:
               run: |
                   set -euo pipefail
 
-                  echo "Install ACM"
                   cd ./generic/openshift/dual-region/procedure/acm/
-                  ./install-acm.sh
+
+                  echo "Install ACM"
+                  if ! ./install-acm.sh 2>&1; then
+                    echo "ACM installation failed."
+                    exit 1
+                  fi
+
                   ./verify-acm.sh
 
                   echo "Configure MultiClusterHub"
-                  ./install-multi-cluster-hub.sh
+                  if ! ./install-multi-cluster-hub.sh 2>&1; then
+                    echo "MultiClusterHub installation failed."
+                    exit 1
+                  fi
+
                   ./verify-multi-cluster-hub.sh
 
                   echo "Configure ManagedClusterSet"
-                  ./install-managed-cluster-set.sh
+                  if ! ./install-managed-cluster-set.sh 2>&1; then
+                    echo "ManagedClusterSet installation failed."
+                    exit 1
+                  fi
+
                   ./verify-managed-cluster-set.sh
 
                   echo "Import Cluster 2 in the ManagedClusterSet"
-                  ./initiate-cluster-set.sh
-                  ./verify-managed-cluster-set.sh
+                  if ! ./initiate-cluster-set.sh 2>&1; then
+                    echo "Cluster 2 import to ManagedClusterSet failed."
+                    exit 1
+                  fi
 
+                  ./verify-managed-cluster-set.sh
 
             - name: 🐠 Configure Submariner
               timeout-minutes: 20
@@ -595,13 +668,38 @@ jobs:
                     kubectl --context="$CLUSTER_2_NAME" -n "$CAMUNDA_NAMESPACE_2" logs "$pod_name"
                   done
 
+    integration-tests-retry:
+        name: Retry Tests in case of failure
+        if: failure() && fromJSON(github.run_attempt) < 3 && inputs.notify_back_error_message == ''
+        runs-on: ubuntu-latest
+        needs:
+            - integration-tests
+        steps:
+            - name: Retrigger job
+              uses: camunda/infra-global-github-actions/rerun-failed-run@d9a4c94ace01e82cb4cef3fa8e809d715ac46894 # main
+              with:
+                  error-messages: |
+                      ACM installation failed
+                      MultiClusterHub installation failed
+                      ManagedClusterSet installation failed
+                      Cluster 2 import to ManagedClusterSet failed
+                      The action '🚢 Configure ACM' has timed out after
+                  run-id: ${{ github.run_id }}
+                  repository: ${{ github.repository }}
+                  vault-addr: ${{ secrets.VAULT_ADDR }}
+                  vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
+                  vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
+                  notify-back-on-error: 'true'
+
+
     cleanup-clusters:
         name: Cleanup ROSA clusters
-        if: always()
+        if: always() && needs.integration-tests-retry.result != 'success'
         runs-on: ubuntu-latest
         needs:
             - clusters-info
             - integration-tests
+            - integration-tests-retry
         strategy:
             fail-fast: false
             matrix:
@@ -666,6 +764,7 @@ jobs:
     report-success:
         name: Report success
         runs-on: ubuntu-latest
+        if: success()
         needs:
             - integration-tests
             - cleanup-clusters
@@ -681,9 +780,11 @@ jobs:
 
     report-failure:
         name: Report failures
-        if: failure()
+        if: failure() && (needs.integration-tests-retry.result != 'success' || fromJSON(github.run_attempt) >= 3 || inputs.notify_back_error_message !=
+            '')
         runs-on: ubuntu-latest
         needs:
+            - integration-tests-retry
             - report-success
         steps:
             - name: Notify in Slack in case of failure
