ci: skip teardown for now

diff --git a/.github/workflows/aws_kubernetes_eks_dual_region_tests.yml b/.github/workflows/aws_kubernetes_eks_dual_region_tests.yml
--- a/.github/workflows/aws_kubernetes_eks_dual_region_tests.yml
+++ b/.github/workflows/aws_kubernetes_eks_dual_region_tests.yml
@@ -223,103 +223,103 @@ jobs:
                   region-0-values-yaml: ${{ github.workspace }}/aws/kubernetes/eks-dual-region/helm-values/region0/camunda-values.yaml
                   region-1-values-yaml: ${{ github.workspace }}/aws/kubernetes/eks-dual-region/helm-values/region1/camunda-values.yaml
 
-    cleanup-clusters:
-        runs-on: ubuntu-latest
-        timeout-minutes: 60
-        if: always()
-        needs:
-            - integration-tests
-            - prepare-clusters
-            - clusters-info
-        strategy:
-            fail-fast: false
-            matrix:
-                distro: ${{ fromJson(needs.clusters-info.outputs.platform-matrix).distro }}
-                scenario: ${{ fromJson(needs.clusters-info.outputs.platform-matrix).scenario }}
-        steps:
-            ################## Checkout ##################
-            - name: Checkout repository
-              uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
-            ############# Tool Installation ##############
-            - name: Install asdf tools with cache
-              uses: camunda/infraex-common-config/./.github/actions/asdf-install-tooling@193a21e1e56c9a65517a822224ac3b4ffa4d6ae4 # 1.5.9
-            - name: Configure AWS CLI
-              uses: ./.github/actions/aws-configure-cli
-              with:
-                  vault-addr: ${{ secrets.VAULT_ADDR }}
-                  vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
-                  vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
-                  aws-profile: ${{ env.AWS_PROFILE }}
-                  aws-region: ${{ env.AWS_REGION }}
-            ################ Env Helper ###################
-            - name: Set current target branch
-              id: target-branch
-              run: |
-                  set -euo pipefail
-                  TARGET_BRANCH=$(cat .target-branch)
-                  echo "TARGET_BRANCH=$TARGET_BRANCH" | tee -a "$GITHUB_OUTPUT"
-            - name: Export S3_BACKEND_BUCKET based on matrix
-              id: s3_prefix
-              run: |
-                  set -euo pipefail
-                  echo "S3_BACKEND_BUCKET_PREFIX=aws/kubernetes/${{ matrix.scenario.name }}/" | tee -a "$GITHUB_OUTPUT"
-            ########### KubeConfig Generation ############
-            - name: Export Cluster Name
-              run: |
-                  echo "CLUSTER_NAME=${{ matrix.distro.clusterName }}-${{matrix.scenario.shortName }}" >> "$GITHUB_ENV"
-            - name: KubeConfig generation
-              if: env.CLEANUP_CLUSTERS == 'true'
-              working-directory: ./aws/kubernetes/eks-dual-region/test/
-              timeout-minutes: 5
-              run: |
-                  go test --count=1 -v -timeout 4m -run TestAWSKubeConfigCreation
-    ########### Load Balancer Removal ############
-            - name: Delete LBs to unblock teardown
-              if: env.CLEANUP_CLUSTERS == 'true'
-              working-directory: ./aws/kubernetes/eks-dual-region/test/
-              timeout-minutes: 5
-              run: |
-                  go test --count=1 -v -timeout 4m -run TestClusterCleanup
-    ############# Terratest Teardown #############
-            - name: Delete on-demand EKS Cluster
-              uses: ./.github/actions/aws-generic-terraform-cleanup
-              if: always() && env.CLEANUP_CLUSTERS == 'true'
-              timeout-minutes: 125
-              with:
-                  tf-bucket: ${{ env.S3_BACKEND_BUCKET }}
-                  tf-bucket-region: ${{ env.S3_BUCKET_REGION }}
-                  max-age-hours: 0
-                  target: ${{ matrix.distro.clusterName }}-${{matrix.scenario.shortName }}
-                  tf-bucket-key-prefix: ${{ steps.s3_prefix.outputs.S3_BACKEND_BUCKET_PREFIX }}${{ steps.target-branch.outputs.TARGET_BRANCH }}/
-                  modules-order: clusters
+    # cleanup-clusters:
+    #     runs-on: ubuntu-latest
+    #     timeout-minutes: 60
+    #     if: always()
+    #     needs:
+    #         - integration-tests
+    #         - prepare-clusters
+    #         - clusters-info
+    #     strategy:
+    #         fail-fast: false
+    #         matrix:
+    #             distro: ${{ fromJson(needs.clusters-info.outputs.platform-matrix).distro }}
+    #             scenario: ${{ fromJson(needs.clusters-info.outputs.platform-matrix).scenario }}
+    #     steps:
+    #         ################## Checkout ##################
+    #         - name: Checkout repository
+    #           uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
+    #         ############# Tool Installation ##############
+    #         - name: Install asdf tools with cache
+    #           uses: camunda/infraex-common-config/./.github/actions/asdf-install-tooling@193a21e1e56c9a65517a822224ac3b4ffa4d6ae4 # 1.5.9
+    #         - name: Configure AWS CLI
+    #           uses: ./.github/actions/aws-configure-cli
+    #           with:
+    #               vault-addr: ${{ secrets.VAULT_ADDR }}
+    #               vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
+    #               vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
+    #               aws-profile: ${{ env.AWS_PROFILE }}
+    #               aws-region: ${{ env.AWS_REGION }}
+    #         ################ Env Helper ###################
+    #         - name: Set current target branch
+    #           id: target-branch
+    #           run: |
+    #               set -euo pipefail
+    #               TARGET_BRANCH=$(cat .target-branch)
+    #               echo "TARGET_BRANCH=$TARGET_BRANCH" | tee -a "$GITHUB_OUTPUT"
+    #         - name: Export S3_BACKEND_BUCKET based on matrix
+    #           id: s3_prefix
+    #           run: |
+    #               set -euo pipefail
+    #               echo "S3_BACKEND_BUCKET_PREFIX=aws/kubernetes/${{ matrix.scenario.name }}/" | tee -a "$GITHUB_OUTPUT"
+    #         ########### KubeConfig Generation ############
+    #         - name: Export Cluster Name
+    #           run: |
+    #               echo "CLUSTER_NAME=${{ matrix.distro.clusterName }}-${{matrix.scenario.shortName }}" >> "$GITHUB_ENV"
+    #         - name: KubeConfig generation
+    #           if: env.CLEANUP_CLUSTERS == 'true'
+    #           working-directory: ./aws/kubernetes/eks-dual-region/test/
+    #           timeout-minutes: 5
+    #           run: |
+    #               go test --count=1 -v -timeout 4m -run TestAWSKubeConfigCreation
+    # ########### Load Balancer Removal ############
+    #         - name: Delete LBs to unblock teardown
+    #           if: env.CLEANUP_CLUSTERS == 'true'
+    #           working-directory: ./aws/kubernetes/eks-dual-region/test/
+    #           timeout-minutes: 5
+    #           run: |
+    #               go test --count=1 -v -timeout 4m -run TestClusterCleanup
+    # ############# Terratest Teardown #############
+    #         - name: Delete on-demand EKS Cluster
+    #           uses: ./.github/actions/aws-generic-terraform-cleanup
+    #           if: always() && env.CLEANUP_CLUSTERS == 'true'
+    #           timeout-minutes: 125
+    #           with:
+    #               tf-bucket: ${{ env.S3_BACKEND_BUCKET }}
+    #               tf-bucket-region: ${{ env.S3_BUCKET_REGION }}
+    #               max-age-hours: 0
+    #               target: ${{ matrix.distro.clusterName }}-${{matrix.scenario.shortName }}
+    #               tf-bucket-key-prefix: ${{ steps.s3_prefix.outputs.S3_BACKEND_BUCKET_PREFIX }}${{ steps.target-branch.outputs.TARGET_BRANCH }}/
+    #               modules-order: clusters
 
-    report-success:
-        name: Report success
-        runs-on: ubuntu-latest
-        needs:
-            - integration-tests
-            - cleanup-clusters
-        steps:
-            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
+    # report-success:
+    #     name: Report success
+    #     runs-on: ubuntu-latest
+    #     needs:
+    #         - integration-tests
+    #         - cleanup-clusters
+    #     steps:
+    #         - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
 
-            - name: Prevent other runs for renovate
-              if: ${{ env.IS_RENOVATE_PR == 'true' }}
-              env:
-                  GH_TOKEN: ${{ github.token }}
-              uses: ./.github/actions/internal-apply-skip-label
+    #         - name: Prevent other runs for renovate
+    #           if: ${{ env.IS_RENOVATE_PR == 'true' }}
+    #           env:
+    #               GH_TOKEN: ${{ github.token }}
+    #           uses: ./.github/actions/internal-apply-skip-label
 
-    report-failure:
-        name: Report failures
-        if: failure()
-        runs-on: ubuntu-latest
-        needs:
-            - report-success
-        steps:
-            - name: Notify in Slack in case of failure
-              id: slack-notification
-              if: ${{ env.IS_SCHEDULE == 'true' }}
-              uses: camunda/infraex-common-config/.github/actions/report-failure-on-slack@193a21e1e56c9a65517a822224ac3b4ffa4d6ae4 # 1.5.9
-              with:
-                  vault_addr: ${{ secrets.VAULT_ADDR }}
-                  vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
-                  vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
+    # report-failure:
+    #     name: Report failures
+    #     if: failure()
+    #     runs-on: ubuntu-latest
+    #     needs:
+    #         - report-success
+    #     steps:
+    #         - name: Notify in Slack in case of failure
+    #           id: slack-notification
+    #           if: ${{ env.IS_SCHEDULE == 'true' }}
+    #           uses: camunda/infraex-common-config/.github/actions/report-failure-on-slack@193a21e1e56c9a65517a822224ac3b4ffa4d6ae4 # 1.5.9
+    #           with:
+    #               vault_addr: ${{ secrets.VAULT_ADDR }}
+    #               vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
+    #               vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
