fix error prone cmd

diff --git a/.github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml b/.github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml
--- a/.github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml
+++ b/.github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml
@@ -242,75 +242,48 @@ jobs:
                   rm encrypted_kubeconfig.enc
                   chmod 600 "$HOME/.kube/config"
 
-            - name: ⏳ Wait for a minimal age of 5min of the cluster
-              id: wait_cluster_age
-              # we need to retry due as the cluster has just been created and the permissions are sometime refused
-              # the minimal age is here to prevent following commands/script to fail
+            - name: 🏗️ Prepare a fresh namespace for the tests
+              # we need to retry due as the cluster has just been created and the OIDC provider may not be available yet
               uses: nick-fields/retry@7152eba30c6575329ac0576536151aca5a72780e # v3
               with:
-                  timeout_minutes: 30
-                  max_attempts: 80
+                  timeout_minutes: 10
+                  max_attempts: 40
                   shell: bash
                   retry_wait_seconds: 15
                   command: |
-                      : # see https://github.com/nick-fields/retry/issues/133
-                      set -o errexit
+                      set -o errexit # this is required https://github.com/nick-fields/retry/issues/133
                       set -o pipefail
 
-                      ns_age=0
-                      ns_name='default'
-                      minimal_age=20
+                      # Delete the namespace to ensure a fresh start
+                      if kubectl get namespace "$TEST_NAMESPACE" &>/dev/null; then
+                        kubectl delete namespace "$TEST_NAMESPACE" --wait
+                        while kubectl get namespace "$TEST_NAMESPACE" &>/dev/null; do
+                          echo "Namespace $TEST_NAMESPACE still being deleted, waiting..."
+                          sleep 5
+                        done
+                      fi
 
-                      while [ "$ns_age" -lt $minimal_age ]; do
-                        current_time=$(date +%s)
-
-                        ns_creation_time_raw=$(oc get ns "$ns_name" -o jsonpath='{.metadata.creationTimestamp}')
-                        ns_creation_time=$(date -d "$ns_creation_time_raw" +%s)
-
-                        echo "Namespace '$ns_name' creation timestamp (seconds): $ns_creation_time"
-                        ns_age=$(( (current_time - ns_creation_time) / 60 ))
-
-                        echo "Namespace '$ns_name' age in minutes: $ns_age"
-
-                        # If ns_age is still less than $minimal_age, wait for a bit and check again
-                        if [ "$ns_age" -lt $minimal_age ]; then
-                          echo "⏳ Waiting for namespace '$ns_name' to be at least $minimal_age minutes old..."
-                          sleep 30
-                        fi
-                      done
-
-                      echo "✅ Namespace '$ns_name' is older than $minimal_age minutes."
-
-            - name: 🏗️ Prepare a fresh namespace for the tests
-              id: kube_config
-              run: |
-                  set -euxo pipefail # tolerate, nothing.
-
-
-                  # Delete the namespace to ensure a fresh start
-                  if kubectl get namespace "$TEST_NAMESPACE" &>/dev/null; then
-                    kubectl delete namespace "$TEST_NAMESPACE" --wait
-                    while kubectl get namespace "$TEST_NAMESPACE" &>/dev/null; do
-                      echo "Namespace $TEST_NAMESPACE still being deleted, waiting..."
-                      sleep 5
-                    done
-                  fi
-
-                  kubectl create namespace "$TEST_NAMESPACE"
+                      kubectl create namespace "$TEST_NAMESPACE"
 
             - name: 🛠️ Assemble deployment values of generic/openshift/single-region
+              timeout-minutes: 10
               run: |
                   set -euxo pipefail # tolerate, nothing.
+
+                  # some commands are prone to error on OpenShift
+                  GOBIN="$HOME/.local/bin"
+                  echo "GOBIN=$GOBIN" | tee -a "$GITHUB_ENV"
+                  go install github.com/joshdk/retry@v1.4.0
 
                   echo "Construct the values.yml file"
 
                   cp generic/openshift/single-region/helm-values/base.yml ./values.yml
 
-                  source ./generic/openshift/single-region/procedure/setup-application-domain.sh
+                  retry -max-time=120s source ./generic/openshift/single-region/procedure/setup-application-domain.sh
                   echo "CAMUNDA_DOMAIN=$DOMAIN_NAME" | tee -a "$GITHUB_ENV"
 
-                  source ./generic/openshift/single-region/procedure/get-ingress-http2-status.sh
-                  ./generic/openshift/single-region/procedure/enable-ingress-http2.sh
+                  retry -max-time=120s source ./generic/openshift/single-region/procedure/get-ingress-http2-status.sh
+                  retry -max-time=120s ./generic/openshift/single-region/procedure/enable-ingress-http2.sh
 
                   # Enable Routes
                   yq '. *d load("generic/openshift/single-region/helm-values/zeebe-gateway-route.yml")' values.yml > values-result.yml
@@ -531,9 +504,9 @@ jobs:
                   temp_output=$(mktemp)
                   echo "$check_zeebe_topology_output" > "$temp_output"
 
-                  # Order each file
-                  yq e '.brokers |= sort_by(.host) | .brokers[] |= (.partitions |= sort_by(.partitionId))' -i "$temp_output"
-                  yq e '.brokers |= sort_by(.host) | .brokers[] |= (.partitions |= sort_by(.partitionId))' -i "$reference_file"
+                  # Order each file also remove not predictable fields
+                  yq e '.brokers |= sort_by(.host) | .brokers[] |= (.partitions |= sort_by(.partitionId) | .partitions[].role = "NOT_PREDICTABLE")' -i "$temp_output"
+                  yq e '.brokers |= sort_by(.host) | .brokers[] |= (.partitions |= sort_by(.partitionId) | .partitions[].role = "NOT_PREDICTABLE")' -i "$reference_file"
 
                   # Compare the two files using diff (in compacted JSON format)
                   diff_output=$(delta <(jq -S . "$temp_output") <(jq -S . "$reference_file"))
