feat(openshift): private vpc and vpn ra alternative (#336)

diff --git a/.github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml b/.github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml
--- a/.github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml
+++ b/.github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml
@@ -190,6 +190,7 @@ jobs:
                   cluster-name: ${{ matrix.distro.clusterName }}-${{matrix.scenario.shortName }}
                   admin-username: ${{ steps.secrets.outputs.CI_OPENSHIFT_MAIN_USERNAME }}
                   admin-password: ${{ steps.secrets.outputs.CI_OPENSHIFT_MAIN_PASSWORD }}
+                  private-vpc: ${{ matrix.distro.private_vpc }}
                   aws-region: ${{ env.AWS_REGION }}
                   s3-backend-bucket: ${{ env.S3_BACKEND_BUCKET }}
                   s3-bucket-region: ${{ env.S3_BUCKET_REGION }}
@@ -198,6 +199,8 @@ jobs:
                   tf-modules-revision: ${{ github.ref }}
                   tf-modules-path: ${{ env.TF_MODULES_DIRECTORY }}
                   cleanup-tf-modules-path: 'false'
+
+                  vpn-enabled: ${{ matrix.distro.private_vpc }}
 
                   tags: >
                       {
@@ -210,16 +213,23 @@ jobs:
                         "ci-repo": "${{ github.repository }}",
                         "ci-event": "${{ github.event_name }}"
                       }
-
             - name: Dump kubeconfig before encryption
               run: |
-                  kubectl config view --raw > "${{ runner.temp }}/kubeconfig.yaml"
+                  set -euo pipefail
 
+                  kubectl config view --raw > "${{ runner.temp }}/kubeconfig.yaml"
             - name: Export kubeconfig and encrypt it # this is required to pass matrix outputs securely using artifacts
               id: export_kube_config
               uses: ./.github/actions/internal-generic-encrypt-export
               with:
                   file_path: ${{ runner.temp }}/kubeconfig.yaml
+                  encryption_key: ${{ steps.secrets.outputs.CI_ENCRYPTION_KEY }}
+
+            - name: Export VPN config and encrypt it
+              id: export_configs
+              uses: ./.github/actions/internal-generic-encrypt-export
+              with:
+                  file_path: ${{ steps.create_cluster.outputs.vpn-client-config-file }}
                   encryption_key: ${{ steps.secrets.outputs.CI_ENCRYPTION_KEY }}
 
             ## Write for matrix outputs workaround
@@ -230,20 +240,44 @@ jobs:
                   matrix-key: ${{ matrix.distro.name }}-${{ matrix.scenario.name }}
                   outputs: |-
                       kubeconfig_encrypted: ${{ steps.export_kube_config.outputs.encrypted_file_base64 }}
+                      vpnconfig_encrypted: ${{ steps.export_configs.outputs.encrypted_file_base64 }}
 
             - name: 🌐 Post-creation steps
               timeout-minutes: 20
               run: |
                   set -euo pipefail
 
-                  # Here we verify the extraction of the env variables as presented in the documentation
+                  # Conditionally gather VPN config if private VPC is enabled
+                  if [[ "${{ matrix.distro.private_vpc }}" == "true" ]]; then
+                    echo "🔒 Private VPC is enabled. Gathering VPN client config..."
+                    cd ${{ env.TF_MODULES_DIRECTORY }}aws/openshift/${{ matrix.scenario.name }}/terraform/vpn/
+                    ./../../procedure/gather-vpn-config.sh
 
-                  cd ${{ env.TF_MODULES_DIRECTORY }}aws/openshift/${{ matrix.scenario.name }}/
-                  source ./procedure/gather-cluster-login-id.sh
+                    # Verify that the .ovpn file was created and is not empty
+                    if [[ -s "my-client.ovpn" ]]; then
+                      echo "✅ VPN config file 'my-client.ovpn' created successfully."
+                    else
+                      echo "❌ ERROR: 'my-client.ovpn' is missing or empty."
+                      exit 1
+                    fi
+
+                    cd -
+                  fi
+
+                  # Here we verify the extraction of the env variables as presented in the documentation
+                  cd ${{ env.TF_MODULES_DIRECTORY }}aws/openshift/${{ matrix.scenario.name }}/terraform/cluster/
+                  source ./../../procedure/gather-cluster-login-id.sh
                   cd -
 
                   echo "CLUSTER_NAME=$CLUSTER_NAME"
                   echo "CLUSTER_API_URL=$CLUSTER_API_URL"
+
+                  if [[ -z "$CLUSTER_NAME" || -z "$CLUSTER_API_URL" ]]; then
+                    echo "❌ ERROR: CLUSTER_NAME or CLUSTER_API_URL is empty."
+                    exit 1
+                  else
+                    echo "✅ Environment variables were successfully extracted."
+                  fi
 
     access-info:
         name: Read kube configs from matrix
@@ -305,6 +339,36 @@ jobs:
                       secret/data/products/infrastructure-experience/ci/common CI_CAMUNDA_USER_TEST_CLIENT_SECRET;
                       secret/data/products/infrastructure-experience/ci/common CI_ENCRYPTION_KEY;
 
+            - name: 🛡️ Install OpenVPN Client
+              if: ${{ matrix.distro.private_vpc == true }}
+              run: |
+                  set -euo pipefail
+
+                  sudo apt update
+                  sudo apt install -y openvpn openvpn-systemd-resolved
+
+            - name: 🛡️ Retrieve VPN Config from outputs
+              uses: ./.github/actions/internal-generic-decrypt-import
+              if: ${{ matrix.distro.private_vpc == true }}
+              with:
+                  output_path: ${{ github.workspace }}/.vpn/client.ovpn
+                  encrypted_file_base64: >
+                      ${{ fromJson(needs.access-info.outputs.config).vpnconfig_encrypted[
+                        format(
+                          '{0}-{1}',
+                          matrix.distro.name,
+                          matrix.scenario.name
+                        )
+                      ] }}
+                  encryption_key: ${{ steps.secrets.outputs.CI_ENCRYPTION_KEY }}
+
+            - name: 🛡️ Connect to VPN
+              if: ${{ matrix.distro.private_vpc == true }}
+              uses: kota65535/github-openvpn-connect-action@cd2ed8a90cc7b060dc4e001143e811b5f7ea0af5 # v3.1.0
+              with:
+                  config_file: ${{ github.workspace }}/.vpn/client.ovpn
+                  echo_config: 'false'
+
             - name: 🔐 Retrieve kubeconfig from outputs
               uses: ./.github/actions/internal-generic-decrypt-import
               with:
@@ -322,6 +386,8 @@ jobs:
             - name: 🔐 Login into the cluster
               timeout-minutes: 2
               run: |
+                  set -euo pipefail
+
                   mkdir -p "$HOME/.kube"
                   mv "${{ runner.temp }}/kubeconfig" "$HOME/.kube/config"
 
