chore: renable all tests again since its working now

diff --git a/.github/workflows/aws_openshift_rosa_hcp_dual_region_tests.yml b/.github/workflows/aws_openshift_rosa_hcp_dual_region_tests.yml
--- a/.github/workflows/aws_openshift_rosa_hcp_dual_region_tests.yml
+++ b/.github/workflows/aws_openshift_rosa_hcp_dual_region_tests.yml
@@ -120,7 +120,7 @@ jobs:
               id: matrix
               with:
                   ci_matrix_file: ${{ env.CI_MATRIX_FILE }}
-                  cluster_name: hci-c557b # TODO: ${{ inputs.cluster_name }}
+                  cluster_name: ${{ inputs.cluster_name }}
                   ref_arch: ${{ inputs.ref-arch }}
                   is_schedule: ${{ env.IS_SCHEDULE }}
                   is_renovate_pr: ${{ env.IS_RENOVATE_PR }}
@@ -643,32 +643,32 @@ jobs:
                   CAMUNDA_VERSION=$(cat .camunda-version)
                   echo "CAMUNDA_VERSION=$CAMUNDA_VERSION" | tee -a "$GITHUB_OUTPUT"
 
-            # - name: 🧪 Run Helm Chart tests
-            #   if: env.TESTS_ENABLED == 'true'
-            #   timeout-minutes: 60
-            #   uses: ./.github/actions/internal-camunda-chart-tests
-            #   with:
-            #       secrets: ${{ toJSON(secrets) }}
-            #       camunda-version: ${{ steps.camunda-version.outputs.CAMUNDA_VERSION }}
-            #       tests-camunda-helm-chart-repo-ref: ${{ env.TESTS_CAMUNDA_HELM_CHART_REPO_REF }}
-            #       tests-camunda-helm-chart-repo-path: ${{ env.TESTS_CAMUNDA_HELM_CHART_REPO_PATH }}
-            #       test-cluster-type: ${{ env.TEST_CLUSTER_TYPE }}
-            #       enable-helm-chart-tests: 'false' # TODO: integrate helm chart dual region tests if they exists
-            #       zeebe-authenticated: 'false'
-            #       zeebe-topology-check-script: ./generic/kubernetes/dual-region/procedure/check-zeebe-cluster-topology.sh
-            #       zeebe-topology-golden-file: ./generic/kubernetes/dual-region/procedure/check-zeebe-cluster-topology-output.json
-            #       camunda-namespace-1: ${{ env.CAMUNDA_NAMESPACE_1 }}
-            #       cluster-2-name: ${{ env.CLUSTER_2_NAME }}
-            #       camunda-namespace-2: ${{ env.CAMUNDA_NAMESPACE_2 }}
-            #       test-release-name: ${{ env.CAMUNDA_RELEASE_NAME }}
-            #       test-client-id: ${{ steps.secrets.outputs.CI_CAMUNDA_USER_TEST_CLIENT_ID }}
-            #       test-client-secret: ${{ steps.secrets.outputs.CI_CAMUNDA_USER_TEST_CLIENT_SECRET }}
-            #       # Disable C8-SM-CHECKS for dual region
-            #       enable-c8sm-deployment-check: 'false'
-            #       enable-c8sm-connectivity-check: 'false'
-            #       enable-c8sm-irsa-check: 'false'
-            #       enable-c8sm-zeebe-token-check: 'false'
-            #       enable-c8sm-zeebe-connectivity-check: 'false'
+            - name: 🧪 Run Helm Chart tests
+              if: env.TESTS_ENABLED == 'true'
+              timeout-minutes: 60
+              uses: ./.github/actions/internal-camunda-chart-tests
+              with:
+                  secrets: ${{ toJSON(secrets) }}
+                  camunda-version: ${{ steps.camunda-version.outputs.CAMUNDA_VERSION }}
+                  tests-camunda-helm-chart-repo-ref: ${{ env.TESTS_CAMUNDA_HELM_CHART_REPO_REF }}
+                  tests-camunda-helm-chart-repo-path: ${{ env.TESTS_CAMUNDA_HELM_CHART_REPO_PATH }}
+                  test-cluster-type: ${{ env.TEST_CLUSTER_TYPE }}
+                  enable-helm-chart-tests: 'false' # TODO: integrate helm chart dual region tests if they exists
+                  zeebe-authenticated: 'false'
+                  zeebe-topology-check-script: ./generic/kubernetes/dual-region/procedure/check-zeebe-cluster-topology.sh
+                  zeebe-topology-golden-file: ./generic/kubernetes/dual-region/procedure/check-zeebe-cluster-topology-output.json
+                  camunda-namespace-1: ${{ env.CAMUNDA_NAMESPACE_1 }}
+                  cluster-2-name: ${{ env.CLUSTER_2_NAME }}
+                  camunda-namespace-2: ${{ env.CAMUNDA_NAMESPACE_2 }}
+                  test-release-name: ${{ env.CAMUNDA_RELEASE_NAME }}
+                  test-client-id: ${{ steps.secrets.outputs.CI_CAMUNDA_USER_TEST_CLIENT_ID }}
+                  test-client-secret: ${{ steps.secrets.outputs.CI_CAMUNDA_USER_TEST_CLIENT_SECRET }}
+                  # Disable C8-SM-CHECKS for dual region
+                  enable-c8sm-deployment-check: 'false'
+                  enable-c8sm-connectivity-check: 'false'
+                  enable-c8sm-irsa-check: 'false'
+                  enable-c8sm-zeebe-token-check: 'false'
+                  enable-c8sm-zeebe-connectivity-check: 'false'
 
             - name: Run Multi-region tests
               if: env.TESTS_ENABLED == 'true'
@@ -715,122 +715,122 @@ jobs:
                     kubectl --context="$CLUSTER_2_NAME" -n "$CAMUNDA_NAMESPACE_2" logs "$pod_name"
                   done
 
-    # integration-tests-retry:
-    #     name: Retry Tests in case of failure
-    #     if: failure() && fromJSON(github.run_attempt) < 3
-    #     runs-on: ubuntu-latest
-    #     needs:
-    #         - integration-tests
-    #     steps:
-    #         - name: Retrigger job
-    #           uses: camunda/infra-global-github-actions/rerun-failed-run@98d1314ca835f199797565423661bc1a66acc802 # main
-    #           with:
-    #               error-messages: '' # retry no matter the error as we want to ensure that the last retries will trigger the cleanup
-    #               run-id: ${{ github.run_id }}
-    #               repository: ${{ github.repository }}
-    #               vault-addr: ${{ secrets.VAULT_ADDR }}
-    #               vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
-    #               vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
+    integration-tests-retry:
+        name: Retry Tests in case of failure
+        if: failure() && fromJSON(github.run_attempt) < 3
+        runs-on: ubuntu-latest
+        needs:
+            - integration-tests
+        steps:
+            - name: Retrigger job
+              uses: camunda/infra-global-github-actions/rerun-failed-run@98d1314ca835f199797565423661bc1a66acc802 # main
+              with:
+                  error-messages: '' # retry no matter the error as we want to ensure that the last retries will trigger the cleanup
+                  run-id: ${{ github.run_id }}
+                  repository: ${{ github.repository }}
+                  vault-addr: ${{ secrets.VAULT_ADDR }}
+                  vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
+                  vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
 
-    # cleanup-clusters:
-    #     name: Cleanup ROSA clusters
-    #     if: always() && (needs.integration-tests.result == 'success' || fromJson(github.run_attempt) >= 3)
-    #     runs-on: ubuntu-latest
-    #     needs:
-    #         - clusters-info
-    #         - integration-tests
-    #         - integration-tests-retry
-    #     strategy:
-    #         fail-fast: false
-    #         matrix:
-    #             distro: ${{ fromJson(needs.clusters-info.outputs.platform-matrix).distro }}
-    #             scenario: ${{ fromJson(needs.clusters-info.outputs.platform-matrix).scenario }}
+    cleanup-clusters:
+        name: Cleanup ROSA clusters
+        if: always() && (needs.integration-tests.result == 'success' || fromJson(github.run_attempt) >= 3)
+        runs-on: ubuntu-latest
+        needs:
+            - clusters-info
+            - integration-tests
+            - integration-tests-retry
+        strategy:
+            fail-fast: false
+            matrix:
+                distro: ${{ fromJson(needs.clusters-info.outputs.platform-matrix).distro }}
+                scenario: ${{ fromJson(needs.clusters-info.outputs.platform-matrix).scenario }}
 
-    #     steps:
-    #         - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
-    #           if: env.CLEANUP_CLUSTERS == 'true'
-    #           with:
-    #               fetch-depth: 0
+        steps:
+            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
+              if: env.CLEANUP_CLUSTERS == 'true'
+              with:
+                  fetch-depth: 0
 
-    #         - name: Install asdf tools with cache
-    #           if: env.CLEANUP_CLUSTERS == 'true'
-    #           uses: camunda/infraex-common-config/./.github/actions/asdf-install-tooling@eb9d51b4dc89deeda7fc160166f378725ee0f06a # 1.5.3
+            - name: Install asdf tools with cache
+              if: env.CLEANUP_CLUSTERS == 'true'
+              uses: camunda/infraex-common-config/./.github/actions/asdf-install-tooling@eb9d51b4dc89deeda7fc160166f378725ee0f06a # 1.5.3
 
-    #         - name: Import Secrets
-    #           id: secrets
-    #           uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3
-    #           if: env.CLEANUP_CLUSTERS == 'true'
-    #           with:
-    #               url: ${{ secrets.VAULT_ADDR }}
-    #               method: approle
-    #               roleId: ${{ secrets.VAULT_ROLE_ID }}
-    #               secretId: ${{ secrets.VAULT_SECRET_ID }}
-    #               exportEnv: false
-    #               secrets: |
-    #                   secret/data/products/infrastructure-experience/ci/common RH_OPENSHIFT_TOKEN;
+            - name: Import Secrets
+              id: secrets
+              uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3
+              if: env.CLEANUP_CLUSTERS == 'true'
+              with:
+                  url: ${{ secrets.VAULT_ADDR }}
+                  method: approle
+                  roleId: ${{ secrets.VAULT_ROLE_ID }}
+                  secretId: ${{ secrets.VAULT_SECRET_ID }}
+                  exportEnv: false
+                  secrets: |
+                      secret/data/products/infrastructure-experience/ci/common RH_OPENSHIFT_TOKEN;
 
-    #         - name: Configure AWS CLI
-    #           uses: ./.github/actions/aws-configure-cli
-    #           if: env.CLEANUP_CLUSTERS == 'true'
-    #           with:
-    #               vault-addr: ${{ secrets.VAULT_ADDR }}
-    #               vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
-    #               vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
-    #               aws-profile: ${{ env.AWS_PROFILE }}
-    #               aws-region: ${{ env.CLUSTER_1_AWS_REGION }}
+            - name: Configure AWS CLI
+              uses: ./.github/actions/aws-configure-cli
+              if: env.CLEANUP_CLUSTERS == 'true'
+              with:
+                  vault-addr: ${{ secrets.VAULT_ADDR }}
+                  vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
+                  vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
+                  aws-profile: ${{ env.AWS_PROFILE }}
+                  aws-region: ${{ env.CLUSTER_1_AWS_REGION }}
 
-    #         - name: Set current target branch
-    #           if: env.CLEANUP_CLUSTERS == 'true'
-    #           id: target-branch
-    #           run: |
-    #               set -euo pipefail
-    #               TARGET_BRANCH=$(cat .target-branch)
-    #               echo "TARGET_BRANCH=$TARGET_BRANCH" | tee -a "$GITHUB_OUTPUT"
+            - name: Set current target branch
+              if: env.CLEANUP_CLUSTERS == 'true'
+              id: target-branch
+              run: |
+                  set -euo pipefail
+                  TARGET_BRANCH=$(cat .target-branch)
+                  echo "TARGET_BRANCH=$TARGET_BRANCH" | tee -a "$GITHUB_OUTPUT"
 
-    #         - name: Delete on-demand ROSA HCP Cluster
-    #           uses: ./.github/actions/aws-generic-terraform-cleanup
-    #           if: always() && env.CLEANUP_CLUSTERS == 'true'
-    #           timeout-minutes: 125
-    #           env:
-    #               RHCS_TOKEN: ${{ steps.secrets.outputs.RH_OPENSHIFT_TOKEN }}
-    #           with:
-    #               tf-bucket: ${{ env.S3_BACKEND_BUCKET }}
-    #               tf-bucket-region: ${{ env.S3_BUCKET_REGION }}
-    #               max-age-hours: 0
-    #               target: ${{ matrix.distro.clusterName }}-${{matrix.scenario.shortName }}
-    #               tf-bucket-key-prefix: ${{ env.S3_BACKEND_BUCKET_PREFIX }}${{ steps.target-branch.outputs.TARGET_BRANCH }}/
-    #               openshift: 'true'
-    #               delete-ghost-rosa-clusters: 'true'
-    #               modules-order: backup_bucket,peering,clusters
-    # report-success:
-    #     name: Report success
-    #     runs-on: ubuntu-latest
-    #     needs:
-    #         - integration-tests
-    #         - cleanup-clusters
-    #     steps:
-    #         - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
+            - name: Delete on-demand ROSA HCP Cluster
+              uses: ./.github/actions/aws-generic-terraform-cleanup
+              if: always() && env.CLEANUP_CLUSTERS == 'true'
+              timeout-minutes: 125
+              env:
+                  RHCS_TOKEN: ${{ steps.secrets.outputs.RH_OPENSHIFT_TOKEN }}
+              with:
+                  tf-bucket: ${{ env.S3_BACKEND_BUCKET }}
+                  tf-bucket-region: ${{ env.S3_BUCKET_REGION }}
+                  max-age-hours: 0
+                  target: ${{ matrix.distro.clusterName }}-${{matrix.scenario.shortName }}
+                  tf-bucket-key-prefix: ${{ env.S3_BACKEND_BUCKET_PREFIX }}${{ steps.target-branch.outputs.TARGET_BRANCH }}/
+                  openshift: 'true'
+                  delete-ghost-rosa-clusters: 'true'
+                  modules-order: backup_bucket,peering,clusters
+    report-success:
+        name: Report success
+        runs-on: ubuntu-latest
+        needs:
+            - integration-tests
+            - cleanup-clusters
+        steps:
+            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
 
-    #         - name: Prevent other runs for renovate
-    #           if: ${{ env.IS_RENOVATE_PR == 'true' }}
-    #           env:
-    #               GH_TOKEN: ${{ github.token }}
-    #           uses: ./.github/actions/internal-apply-skip-label
+            - name: Prevent other runs for renovate
+              if: ${{ env.IS_RENOVATE_PR == 'true' }}
+              env:
+                  GH_TOKEN: ${{ github.token }}
+              uses: ./.github/actions/internal-apply-skip-label
 
 
-    # report-failure:
-    #     name: Report failures
-    #     if: failure() && (needs.integration-tests-retry.result != 'success' || fromJSON(github.run_attempt) >= 3)
-    #     runs-on: ubuntu-latest
-    #     needs:
-    #         - integration-tests-retry
-    #         - report-success
-    #     steps:
-    #         - name: Notify in Slack in case of failure
-    #           id: slack-notification
-    #           if: ${{ env.IS_SCHEDULE == 'true' }}
-    #           uses: camunda/infraex-common-config/.github/actions/report-failure-on-slack@eb9d51b4dc89deeda7fc160166f378725ee0f06a # 1.5.3
-    #           with:
-    #               vault_addr: ${{ secrets.VAULT_ADDR }}
-    #               vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
-    #               vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
+    report-failure:
+        name: Report failures
+        if: failure() && (needs.integration-tests-retry.result != 'success' || fromJSON(github.run_attempt) >= 3)
+        runs-on: ubuntu-latest
+        needs:
+            - integration-tests-retry
+            - report-success
+        steps:
+            - name: Notify in Slack in case of failure
+              id: slack-notification
+              if: ${{ env.IS_SCHEDULE == 'true' }}
+              uses: camunda/infraex-common-config/.github/actions/report-failure-on-slack@eb9d51b4dc89deeda7fc160166f378725ee0f06a # 1.5.3
+              with:
+                  vault_addr: ${{ secrets.VAULT_ADDR }}
+                  vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
+                  vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
