fix eof

diff --git a/.github/workflows/aws_kubernetes_eks_single_region_tests.yml b/.github/workflows/aws_kubernetes_eks_single_region_tests.yml
--- a/.github/workflows/aws_kubernetes_eks_single_region_tests.yml
+++ b/.github/workflows/aws_kubernetes_eks_single_region_tests.yml
@@ -428,25 +428,25 @@ jobs:
                       --set ingressShim.defaultIssuerGroup=cert-manager.io
 
                     cat << EOF | kubectl apply -f -
-                      ---
-                      apiVersion: cert-manager.io/v1
-                      kind: ClusterIssuer
-                      metadata:
-                        name: letsencrypt
-                      spec:
-                        acme:
-                          server: https://acme-v02.api.letsencrypt.org/directory
-                          email: $MAIL
-                          privateKeySecretRef:
-                            name: letsencrypt-issuer-account-key
-                          solvers:
-                            - selector: {}
-                              dns01:
-                                route53:
-                                  region: $REGION
-                                  # Cert-manager will automatically observe the hosted zones
-                                  # Cert-manager will automatically make use of the IRSA assigned service account
-                      EOF
+                    ---
+                    apiVersion: cert-manager.io/v1
+                    kind: ClusterIssuer
+                    metadata:
+                      name: letsencrypt
+                    spec:
+                      acme:
+                        server: https://acme-v02.api.letsencrypt.org/directory
+                        email: $MAIL
+                        privateKeySecretRef:
+                          name: letsencrypt-issuer-account-key
+                        solvers:
+                          - selector: {}
+                            dns01:
+                              route53:
+                                region: $REGION
+                                # Cert-manager will automatically observe the hosted zones
+                                # Cert-manager will automatically make use of the IRSA assigned service account
+                    EOF
 
             - name: 🏗️ Prepare a fresh namespace for the tests
               run: |
@@ -686,14 +686,22 @@ jobs:
                     kubectl -n "$TEST_NAMESPACE" logs "$pod_name";
                   done
 
-            - name: Cleanup Namespace
-              if: always()
-              run: |
-                  set -euo pipefail
+            # - name: Cleanup Namespace
+            #   if: always()
+            #   run: |
+            #       set -euo pipefail
 
-                  helm uninstall camunda --namespace "$TEST_NAMESPACE" --wait
-                  kubectl delete namespace "$TEST_NAMESPACE" --wait
+            #       helm uninstall camunda --namespace "$TEST_NAMESPACE" --wait
+            #       kubectl delete namespace "$TEST_NAMESPACE" --wait
 
+            # - name: Cleanup domain specific resources
+            #   if: always() && ${{ matrix.declination == 'domain' }}
+            #   run: |
+            #       set -euo pipefail
+
+            #       helm uninstall ingress-nginx --namespace ingress-nginx --wait
+            #       helm uninstall external-dns --namespace external-dns --wait
+            #       helm uninstall cert-manager --namespace cert-manager --wait
 
     # cleanup-clusters:
     #     name: Cleanup ROSA clusters
